### ISSUE TITLE
Is your expertise available for hire?

### ISSUE THREAD

**Issue by mstattma** [quietvoid/hevc_parser#1]
I'm having a couple of commercial projects at hand where your knowledge would be a great addition.

**Comment by quietvoid** [comment]
No, all my repos are hobby projects.

**Comment by mstattma** [comment]
Respect, I know few who understand codecs on that level, let alone as hobby. For avoidance of doubt, I had freelance in mind. But either way, thank you for making all this available, I appreciate your work.

**Comment by quietvoid** [comment]
The code in this repo was greatly inspired by https://github.com/virinext/hevcesbrowser
As well as the FFmpeg HEVC code.

I did not do much other than porting it.

**Comment by mstattma** [comment]
Thanks for pointing this out! But I was really referring to the entire work, especially concerning the HDR tools. The profile 5->8.1 conversion made me reach out. I just chose a generic repo for this issue ;)

**Comment by ValZapod** [comment]
> Thanks for pointing this out! But I was really referring to the entire work, especially concerning the HDR tools. The profile 5->8.1 conversion made me reach out. I just chose a generic repo for this issue ;)

No conversion is happening. The real conversion would be to decode IPTPQc2, but that does not happen here.

**Comment by mstattma** [comment]
Yeah I realize now that the RPU conversion also requires a re-encode. Which basically would require a DoVi decode if the profile 5 is all you have. And at least for commercial use that would mean licensing a decoder.

However, we would come a long way when a profile 8.1 encode can be made to play correctly on a profile 5-only device.

Edit: play *correctly*

**Comment by ValZapod** [comment]
> And at least for commercial use that would mean licensing a decoder.

LOL, no. There is a IPTPQc2 decoder [here](https://code.videolan.org/videolan/libplacebo/-/commit/3c19e385edcf165c5253c9c78410fab1d14d10d8): see for full discussion https://code.videolan.org/videolan/libplacebo/-/issues/113
But it is still without reshaping and thus not perfect and will cause changes in color when reshaping changes of IPTPQc2 matrices happens. Not that it is too hard to implement. The hardest thing, believe it or not, is full range YCbCr/IPT.

**Comment by mstattma** [comment]
I don't understand the full range thing tbh, but I'm 100% certain that Dolby's business lies in licensing their patented stuff - especially the decoders.

**Comment by ValZapod** [comment]
> I don't understand the full range thing tbh

Are you even using Nvidia GPU on your PC? there is full range RGB and limited range RGB in nvidia control panel. The same exists in YCbCr domain, even in Nvidia! In HDMI sYCC (and now ICtCp, standard finalised in 2021) and also Adobe YCC YCbCr digital formats can have full and limited range in any bitness, in limited range some values are reserved for synchromisation, while in full none. All video except DV profile 5 is limited range though! Full range is used in JPEG images.

**Comment by mstattma** [comment]
Ah ok, thanks, now I understand :)
